DMSLauncherBundle:
    resource: "@DMSLauncherBundle/Controller/"
    type:     annotation
    prefix:   /

FTCAuthBundle:
    resource: "@FTCAuthBundle/Controller/"
    type:     annotation
    prefix:   /

DMSBaseBundle:
    resource: "@DMSBaseBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
